"""Integrity constants for the packaged synthetic-university archive.

Generated by `node tools/export-synthetic-university.mjs`. Do not edit by
hand: the digest is what lets the seeder trust the archive, and a mismatch
between this file and the archive is exactly the condition it exists to catch.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

#: Repository-relative location of the gzip-compressed universe.
ASSET_RELATIVE_PATH: Final = "demo/synthetic-university-v1.json.gz"

#: SHA-256 of the *compressed* archive exactly as written to disk.
ASSET_SHA256: Final = "7711cd2a3f74fef99299e3921085723a94f8a6311dd3431466a1efc6e51238ca"

#: Byte length of the compressed archive.
ASSET_SIZE_BYTES: Final = 3397599

#: `meta.version` the archive must declare.
UNIVERSE_VERSION: Final = "synthetic-university-v1"

#: Generator inputs that produced the archive.
UNIVERSE_SEED: Final = 20260810
UNIVERSE_STUDENT_COUNT: Final = 3000
UNIVERSE_GENERATED_FOR: Final = "2026-08-05T12:00:00.000Z"

#: Row counts per collection, asserted after decoding.
UNIVERSE_COLLECTION_COUNTS: Final[Mapping[str, int]] = MappingProxyType(
    {
        "students": 3000,
        "applications": 3000,
        "checklistTasks": 22856,
        "documents": 12343,
        "holds": 1316,
        "fafsaRecords": 2516,
        "verificationRequirements": 1390,
        "aidAwards": 5791,
        "disbursements": 1893,
        "sapStatus": 2857,
        "accountLedger": 11389,
        "housingApplications": 1663,
        "housingAssignments": 1061,
        "orientationRegistrations": 1892,
        "registrationEligibility": 2576,
        "internationalRequirements": 2724,
        "terms": 3,
        "programs": 14,
        "advisors": 25,
        "residenceHalls": 6,
        "mealPlans": 4,
        "holdTypes": 5,
        "documentCategories": 8,
        "awardFunds": 8,
        "orientationSessions": 6,
        "costOfAttendance": 6,
        "checklistTaskCatalogue": 8,
        "personas": 10,
    }
)
