apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - api-service.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - api-pdb.yaml
  - worker-pdb.yaml
  - api-network-policy.yaml
  - api-ingress.yaml
