"""Request correlation compatible with the original Fastify adapter."""

import re
from uuid import uuid4

from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.requests import Request
from starlette.responses import Response
from starlette.types import ASGIApp, Message, Receive, Scope, Send

SAFE_REQUEST_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$")
STUDENT_OIDC_CALLBACK_PATHS = frozenset(
    {
        "/v1/auth/sso/google/callback",
        "/v1/auth/sso/microsoft/callback",
    }
)


class OidcCallbackQueryRedactionMiddleware:
    """Keep OIDC response parameters out of server access-log request targets."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http" or scope.get("path") not in STUDENT_OIDC_CALLBACK_PATHS:
            await self.app(scope, receive, send)
            return

        # The application receives a shallow copy containing the real query so
        # FastAPI can validate state and exchange the authorization code. The
        # server retains the original scope, which is scrubbed before its send
        # callable observes response.start and produces an access-log entry.
        application_scope: Scope = dict(scope)

        async def send_with_redacted_scope(message: Message) -> None:
            if message["type"] == "http.response.start":
                scope["query_string"] = b""
            await send(message)

        try:
            await self.app(application_scope, receive, send_with_redacted_scope)
        finally:
            # Also protect error responses generated by an outer server error
            # middleware after the downstream application raises.
            scope["query_string"] = b""


class RequestContextMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        candidate = request.headers.get("x-correlation-id") or request.headers.get("x-request-id")
        request_id = (
            candidate if candidate and SAFE_REQUEST_ID.fullmatch(candidate) else str(uuid4())
        )
        request.state.request_id = request_id
        request.state.trace_id = uuid4().hex
        response = await call_next(request)
        response.headers["x-request-id"] = request_id
        response.headers["x-correlation-id"] = request_id
        response.headers["x-trace-id"] = request.state.trace_id
        return response
