apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/audentra/audentra-platform
    newName: us-central1-docker.pkg.dev/PROJECT_ID/audentra-platform/api
    newTag: REPLACE_WITH_RELEASE_SHA
patches:
  - path: platform-config.yaml
