import type {
  StateEffect,
  StateEffectGraph,
  StateFieldOwnership,
} from "./types";

const STATIC_LINEAGE_WARNING =
  "This graph declares intended CRM semantics. CodeGraphContext adds static call-graph evidence. Neither is runtime lineage; correlate OpenTelemetry spans with audit_event and outbox_event records.";

export function buildStateEffectGraph(input: {
  owners: readonly StateFieldOwnership[];
  effects: readonly StateEffect[];
  generatedAt?: string;
}): StateEffectGraph {
  const nodes = new Map<string, StateEffectGraph["nodes"][number]>();
  const edges: StateEffectGraph["edges"] = [];

  for (const owner of input.owners) {
    nodes.set(`owner:${owner.owner}`, {
      id: `owner:${owner.owner}`,
      type: "owner",
      label: owner.owner,
      owner: owner.owner,
    });
    nodes.set(`field:${owner.field}`, {
      id: `field:${owner.field}`,
      type: "field",
      label: owner.field,
      owner: owner.owner,
    });
    edges.push({
      from: `owner:${owner.owner}`,
      to: `field:${owner.field}`,
      type: "owns",
      runtimeEvidence: false,
    });
  }

  for (const effect of input.effects) {
    nodes.set(`effect:${effect.id}`, {
      id: `effect:${effect.id}`,
      type: "effect",
      label: effect.id,
      owner: effect.owner,
    });
    for (const field of effect.reads) {
      if (!nodes.has(`field:${field}`)) {
        nodes.set(`field:${field}`, {
          id: `field:${field}`,
          type: "field",
          label: field,
        });
      }
      edges.push({
        from: `field:${field}`,
        to: `effect:${effect.id}`,
        type: "reads",
        runtimeEvidence: false,
      });
    }
    for (const field of effect.writes) {
      edges.push({
        from: `effect:${effect.id}`,
        to: `field:${field}`,
        type: "writes",
        runtimeEvidence: false,
      });
    }
    for (const event of effect.emits) {
      nodes.set(`event:${event}`, {
        id: `event:${event}`,
        type: "event",
        label: event,
      });
      edges.push({
        from: `effect:${effect.id}`,
        to: `event:${event}`,
        type: "emits",
        runtimeEvidence: true,
      });
    }
    for (const event of effect.consumes) {
      nodes.set(`event:${event}`, {
        id: `event:${event}`,
        type: "event",
        label: event,
      });
      edges.push({
        from: `event:${event}`,
        to: `effect:${effect.id}`,
        type: "consumes",
        runtimeEvidence: true,
      });
    }
    for (const target of effect.synchronousCalls) {
      edges.push({
        from: `effect:${effect.id}`,
        to: `effect:${target}`,
        type: "calls",
        runtimeEvidence: false,
      });
    }
  }

  return {
    schemaVersion: 1,
    generatedAt: input.generatedAt ?? new Date().toISOString(),
    warning: STATIC_LINEAGE_WARNING,
    owners: input.owners,
    effects: input.effects,
    nodes: [...nodes.values()].sort((a, b) => a.id.localeCompare(b.id)),
    edges: edges.sort((a, b) =>
      `${a.from}:${a.type}:${a.to}`.localeCompare(
        `${b.from}:${b.type}:${b.to}`,
      ),
    ),
  };
}

export function renderStateEffectMermaid(graph: StateEffectGraph): string {
  const lines = [
    "%% Generated by @vv/state-effects. Do not edit by hand.",
    "%% Static declaration only; runtime proof is OTel + audit_event + outbox_event.",
    "flowchart LR",
    "  classDef effect fill:#102A43,color:#fff,stroke:#102A43;",
    "  classDef field fill:#F7F2E8,color:#102A43,stroke:#C99A2E;",
    "  classDef event fill:#E8F3EE,color:#102A43,stroke:#4A8066;",
    "  classDef owner fill:#EEF1F5,color:#102A43,stroke:#7B8794;",
  ];
  const mermaidId = (id: string): string =>
    `n_${Buffer.from(id).toString("hex")}`;
  for (const node of graph.nodes) {
    lines.push(
      `  ${mermaidId(node.id)}["${node.label.replaceAll('"', "'")}"]:::${node.type}`,
    );
  }
  const arrows: Record<StateEffectGraph["edges"][number]["type"], string> = {
    owns: "-->|owns|",
    reads: "-->|reads|",
    writes: "-->|writes|",
    emits: "-->|emits|",
    consumes: "-->|consumes|",
    calls: "-->|sync calls|",
  };
  for (const edge of graph.edges) {
    lines.push(
      `  ${mermaidId(edge.from)} ${arrows[edge.type]} ${mermaidId(edge.to)}`,
    );
  }
  return `${lines.join("\n")}\n`;
}
