import type {
  StateEffect,
  StateFieldOwnership,
} from "./types";

export const stateFieldOwnership = [
  {
    field: "admission.offer.status",
    owner: "admissions",
    description: "Authoritative admission-offer decision state.",
    classification: "sensitive",
  },
  {
    field: "enrollment.journey.status",
    owner: "enrollment",
    description: "Lifecycle state of the student's enrollment journey.",
    classification: "internal",
  },
  {
    field: "enrollment.requirement.status",
    owner: "enrollment",
    description: "Server-confirmed status for an enrollment requirement.",
    classification: "sensitive",
  },
  {
    field: "student.onboarding.status",
    owner: "onboarding",
    description: "Whether first-time onboarding is required or complete.",
    classification: "internal",
  },
  {
    field: "student.onboarding.currentStep",
    owner: "onboarding",
    description: "Next server-authorized onboarding step.",
    classification: "internal",
  },
  {
    field: "student.onboarding.payload",
    owner: "onboarding",
    description: "Versioned first-time student onboarding answers.",
    classification: "sensitive",
  },
  {
    field: "document.status",
    owner: "documents",
    description: "Upload, storage, extraction, and review state.",
    classification: "internal",
  },
  {
    field: "document.extraction",
    owner: "documents",
    description: "Untrusted structured extraction pending student or staff confirmation.",
    classification: "sensitive",
  },
  {
    field: "academics.transcriptCredits",
    owner: "academics",
    description: "Confirmed normalized transcript coursework and exam credit.",
    classification: "sensitive",
  },
  {
    field: "academics.exemptionRecommendations",
    owner: "academics",
    description: "Versioned evidence-based equivalency recommendations.",
    classification: "sensitive",
  },
  {
    field: "financial.deposit.status",
    owner: "financials",
    description: "Authoritative enrollment-deposit payment result.",
    classification: "sensitive",
  },
  {
    field: "financial.requiredDocument.status",
    owner: "financials",
    description: "Verification state for a student financial-aid requirement.",
    classification: "sensitive",
  },
  {
    field: "financial.paymentPlan.status",
    owner: "financials",
    description: "Student payment-plan enrollment state.",
    classification: "sensitive",
  },
  {
    field: "financial.remainingBalanceCents",
    owner: "financials",
    description: "Derived remaining balance from charges, accepted aid, and payments.",
    classification: "sensitive",
  },
  {
    field: "student.profile",
    owner: "student-profile",
    description: "Student-editable profile and communication preferences.",
    classification: "sensitive",
  },
] as const satisfies readonly StateFieldOwnership[];

export const stateEffects = [
  {
    id: "admissions.acceptOffer",
    version: 1,
    owner: "admissions",
    kind: "command",
    handler: "PostgresPlatformStore.acceptAdmissionOffer",
    description: "Accepts an eligible offer and creates the enrollment journey atomically.",
    reads: ["admission.offer.status"],
    writes: [
      "admission.offer.status",
      "enrollment.journey.status",
      "enrollment.requirement.status",
    ],
    emits: [
      "admission.offer_accepted.v1",
      "enrollment.journey_created.v1",
    ],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "onboarding.saveStep",
    version: 1,
    owner: "onboarding",
    kind: "command",
    handler: "PostgresPortalStore.updateStudentOnboarding",
    description: "Validates and saves exactly the next authorized onboarding step.",
    reads: [
      "student.onboarding.status",
      "student.onboarding.currentStep",
      "student.onboarding.payload",
    ],
    writes: [
      "student.onboarding.currentStep",
      "student.onboarding.payload",
    ],
    emits: [],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "expectedVersion",
      scope: "aggregate",
    },
    transaction: {
      boundary: "single_database",
      isolation: "database_default",
    },
  },
  {
    id: "onboarding.complete",
    version: 1,
    owner: "onboarding",
    kind: "command",
    handler: "PostgresPortalStore.completeStudentOnboarding",
    description: "Locks the onboarding record and makes dashboard the future home route.",
    reads: [
      "student.onboarding.currentStep",
      "student.onboarding.payload",
      "financial.deposit.status",
    ],
    writes: ["student.onboarding.status"],
    emits: ["student.onboarding_completed.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.reserveUpload",
    version: 1,
    owner: "documents",
    kind: "command",
    handler: "PostgresPortalStore.reserveStudentDocumentUpload",
    description: "Reserves a content-addressed upload before object storage transfer.",
    reads: [],
    writes: ["document.status"],
    emits: ["document.upload_reserved.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key + sha256",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.completeExtraction",
    version: 1,
    owner: "documents",
    kind: "command",
    handler: "PostgresPortalStore.completeStudentDocumentExtraction",
    description: "Stores model extraction as untrusted reviewable data.",
    reads: ["document.status"],
    writes: [
      "document.status",
      "document.extraction",
      "enrollment.requirement.status",
      "financial.requiredDocument.status",
    ],
    emits: ["document.extraction_completed.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "documentId + extractionAttempt",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "academics.confirmTranscriptExtraction",
    version: 1,
    owner: "academics",
    kind: "command",
    handler: "PostgresPortalStore.confirmStudentDocumentExtraction",
    description: "Confirms transcript data and applies deterministic, versioned equivalency rules.",
    reads: ["document.extraction"],
    writes: [
      "document.status",
      "academics.transcriptCredits",
      "academics.exemptionRecommendations",
      "enrollment.requirement.status",
    ],
    emits: ["student.transcript_credits_imported.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "enrollment.applyDocumentExtraction",
    version: 1,
    owner: "enrollment",
    kind: "event_handler",
    handler: "EnrollmentProjectionHandler.onDocumentExtractionCompleted",
    description: "Projects a reviewed document into the matching enrollment requirement.",
    reads: ["document.status"],
    writes: ["enrollment.requirement.status"],
    emits: [],
    consumes: ["document.extraction_completed.v1"],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "eventId",
      scope: "event",
    },
    transaction: {
      boundary: "single_database",
      isolation: "database_default",
    },
  },
  {
    id: "financials.recordDeposit",
    version: 1,
    owner: "financials",
    kind: "command",
    handler: "PostgresPortalStore.createDepositPayment",
    description: "Records the processor result once and emits the payment fact.",
    reads: ["admission.offer.status", "financial.deposit.status"],
    writes: [
      "financial.deposit.status",
      "enrollment.requirement.status",
      "financial.remainingBalanceCents",
    ],
    emits: ["payment.deposit_succeeded.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "financials.selectPaymentPlan",
    version: 1,
    owner: "financials",
    kind: "command",
    handler: "PostgresPortalStore.selectFinancialPaymentPlan",
    description: "Selects one eligible plan and refreshes the financial projection.",
    reads: [
      "financial.remainingBalanceCents",
      "financial.paymentPlan.status",
    ],
    writes: [
      "financial.paymentPlan.status",
    ],
    emits: ["student_financial.payment_plan_selected.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "studentProfile.update",
    version: 1,
    owner: "student-profile",
    kind: "command",
    handler: "PostgresPortalStore.updateStudentProfile",
    description: "Updates the student-owned profile under optimistic concurrency.",
    reads: ["student.profile"],
    writes: ["student.profile", "enrollment.requirement.status"],
    emits: ["student.profile_updated.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "expectedVersion",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
] as const satisfies readonly StateEffect[];
