import type {
  StateEffect,
  StateFieldOwnership,
} from "./types";

export const stateFieldOwnership = [
  {
    field: "identity.invitation",
    owner: "identity",
    description: "Single-use tenant-scoped link between credential registration and an admitted student.",
    classification: "sensitive",
  },
  {
    field: "identity.account",
    owner: "identity",
    description: "Credential status, normalized contacts, and password-hash metadata.",
    classification: "restricted",
  },
  {
    field: "identity.verification",
    owner: "identity",
    description: "Email and phone verification lifecycle behind delivery adapters.",
    classification: "restricted",
  },
  {
    field: "identity.session",
    owner: "identity",
    description: "Hashed, expiring, and revocable opaque browser sessions.",
    classification: "restricted",
  },
  {
    field: "admission.offer.status",
    owner: "admissions",
    description: "Authoritative admission-offer decision state.",
    classification: "sensitive",
  },
  {
    field: "enrollment.journey.status",
    owner: "enrollment",
    description: "Lifecycle state of the student's enrollment journey.",
    classification: "internal",
  },
  {
    field: "enrollment.requirement.status",
    owner: "enrollment",
    description: "Server-confirmed status for an enrollment requirement.",
    classification: "sensitive",
  },
  {
    field: "student.onboarding.status",
    owner: "onboarding",
    description: "Whether first-time onboarding is required or complete.",
    classification: "internal",
  },
  {
    field: "student.onboarding.currentStep",
    owner: "onboarding",
    description: "Next server-authorized onboarding step.",
    classification: "internal",
  },
  {
    field: "student.onboarding.payload",
    owner: "onboarding",
    description: "Versioned first-time student onboarding answers.",
    classification: "sensitive",
  },
  {
    field: "student.housing.plan",
    owner: "onboarding",
    description: "Student-selected living preference and optional residence choice.",
    classification: "sensitive",
  },
  {
    field: "document.status",
    owner: "documents",
    description: "Upload, storage, extraction, and review state.",
    classification: "internal",
  },
  {
    field: "document.category",
    owner: "documents",
    description: "Content-classified document category, optionally initialized from requirement context.",
    classification: "internal",
  },
  {
    field: "document.processingMode",
    owner: "documents",
    description: "Server-authored policy selecting full agentic extraction, document-type-only classification, or direct staff review.",
    classification: "internal",
  },
  {
    field: "document.requirementId",
    owner: "documents",
    description: "Enrollment requirement that supplied context for an upload.",
    classification: "internal",
  },
  {
    field: "document.extraction",
    owner: "documents",
    description: "Untrusted structured extraction for enabled categories, including normalized identity-photo regions and advisory transcript evidence.",
    classification: "sensitive",
  },
  {
    field: "document.extractionAttempt.providerResponse",
    owner: "documents",
    description: "Internal provider response and transport metadata for a correlated extraction attempt.",
    classification: "sensitive",
  },
  {
    field: "academics.transcriptCredits",
    owner: "academics",
    description: "Normalized transcript coursework and exam evidence; automatic imports remain advisory until registrar review.",
    classification: "sensitive",
  },
  {
    field: "academics.exemptionRecommendations",
    owner: "academics",
    description: "Versioned evidence-based equivalency recommendations.",
    classification: "sensitive",
  },
  {
    field: "financial.deposit.status",
    owner: "financials",
    description: "Authoritative enrollment-deposit payment result.",
    classification: "sensitive",
  },
  {
    field: "financial.requiredDocument.status",
    owner: "financials",
    description: "Verification state for a student financial-aid requirement.",
    classification: "sensitive",
  },
  {
    field: "financial.paymentPlan.status",
    owner: "financials",
    description: "Student payment-plan enrollment state.",
    classification: "sensitive",
  },
  {
    field: "financial.remainingBalanceCents",
    owner: "financials",
    description: "Derived remaining balance from charges, accepted aid, and payments.",
    classification: "sensitive",
  },
  {
    field: "student.profile",
    owner: "student-profile",
    description: "Student-editable profile and communication preferences.",
    classification: "sensitive",
  },
] as const satisfies readonly StateFieldOwnership[];

export const stateEffects = [
  {
    id: "identity.registerCredential",
    version: 1,
    owner: "identity",
    kind: "command",
    implementationStatus: "preview_only",
    handler: null,
    description: "Defines the credential-registration contract exercised by the development preview; the production FastAPI identity adapter is not implemented yet.",
    reads: ["identity.invitation"],
    writes: [
      "identity.invitation",
      "identity.account",
      "identity.verification",
      "identity.session",
    ],
    emits: ["identity.account_registered.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "invitation token + normalized email",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "identity.createSession",
    version: 1,
    owner: "identity",
    kind: "command",
    implementationStatus: "preview_only",
    handler: null,
    description: "Defines the credential-session contract exercised by the development preview; the production FastAPI identity adapter is not implemented yet.",
    reads: ["identity.account"],
    writes: ["identity.account", "identity.session"],
    emits: ["identity.session_created.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "new random session token",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "admissions.acceptOffer",
    version: 1,
    owner: "admissions",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPlatformRepository.accept_admission_offer",
    description: "Accepts an eligible offer and creates the enrollment journey atomically.",
    reads: ["admission.offer.status"],
    writes: [
      "admission.offer.status",
      "enrollment.journey.status",
      "enrollment.requirement.status",
    ],
    emits: [
      "admission.offer_accepted.v1",
      "enrollment.journey_created.v1",
    ],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "onboarding.saveStep",
    version: 1,
    owner: "onboarding",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.update_student_onboarding",
    description: "Validates and saves exactly the next authorized onboarding step.",
    reads: [
      "student.onboarding.status",
      "student.onboarding.currentStep",
      "student.onboarding.payload",
    ],
    writes: [
      "student.onboarding.currentStep",
      "student.onboarding.payload",
      "student.profile",
    ],
    emits: ["student.profile_updated.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "expectedVersion",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "onboarding.complete",
    version: 1,
    owner: "onboarding",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.complete_student_onboarding",
    description: "Locks the onboarding record and makes dashboard the future home route.",
    reads: [
      "student.onboarding.currentStep",
      "student.onboarding.payload",
      "financial.deposit.status",
    ],
    writes: ["student.onboarding.status"],
    emits: ["student.onboarding_completed.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "onboarding.updateHousingPlan",
    version: 1,
    owner: "onboarding",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.update_student_housing_plan",
    description: "Updates a student-owned housing selection and completes its enrollment requirement atomically.",
    reads: ["student.onboarding.payload", "enrollment.requirement.status"],
    writes: [
      "student.onboarding.payload",
      "student.housing.plan",
      "enrollment.requirement.status",
    ],
    emits: ["student.housing_plan_updated.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "expectedVersion",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.reserveUpload",
    version: 1,
    owner: "documents",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.reserve_student_document_upload",
    description: "Commits a recoverable upload reservation before immutable object storage transfer.",
    reads: ["enrollment.requirement.status"],
    writes: [
      "document.status",
      "document.category",
      "document.processingMode",
      "document.requirementId",
    ],
    emits: ["document.upload_reserved.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key + sha256",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.queueExtraction",
    version: 1,
    owner: "documents",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.claim_student_document_processing",
    description: "After object storage succeeds, atomically routes full-extraction and classification-only categories to durable processing, and disabled categories directly to staff review.",
    reads: [
      "document.status",
      "document.processingMode",
      "document.extraction",
    ],
    writes: [
      "document.status",
      "document.extraction",
      "enrollment.requirement.status",
      "financial.requiredDocument.status",
    ],
    emits: [
      "document.extraction_requested.v1",
      "document.stored_for_review.v1",
    ],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "documentId + processing state",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.processQueuedExtraction",
    version: 1,
    owner: "documents",
    kind: "event_handler",
    implementationStatus: "implemented",
    handler: "DocumentExtractionRunner.handle",
    description: "The outbox worker invokes a private authenticated API command; the API reads the immutable original and records a terminal reviewable extraction. Duplicate delivery returns the current terminal document without another model call.",
    reads: ["document.status", "document.category", "document.extraction"],
    writes: [],
    emits: [],
    consumes: ["document.extraction_requested.v1"],
    synchronousCalls: [
      "documents.recordProviderResponse",
      "documents.completeExtraction",
    ],
    idempotency: {
      required: true,
      key: "outbox event id + document processing state",
      scope: "event",
    },
    transaction: {
      boundary: "none",
      isolation: "database_default",
    },
  },
  {
    id: "documents.recordProviderResponse",
    version: 1,
    owner: "documents",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPlatformRepository.record_ai_provider_response",
    description: "Persists the exact provider completion or transport failure separately from the normalized document extraction.",
    reads: ["document.status"],
    writes: ["document.extractionAttempt.providerResponse"],
    emits: [],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "documentId + requestId + attempt",
      scope: "aggregate",
    },
    transaction: {
      boundary: "single_database",
      isolation: "database_default",
    },
  },
  {
    id: "documents.recoverReservedUpload",
    version: 1,
    owner: "documents",
    kind: "event_handler",
    implementationStatus: "implemented",
    handler: "DocumentExtractionRunner.handle",
    description: "The outbox worker invokes a private authenticated recovery command, which verifies immutable storage before queuing extraction after a process interruption.",
    reads: ["document.status", "document.extraction"],
    writes: [],
    emits: [],
    consumes: ["document.upload_reserved.v1"],
    synchronousCalls: ["documents.queueExtraction"],
    idempotency: {
      required: true,
      key: "outbox event id + document processing state",
      scope: "event",
    },
    transaction: {
      boundary: "none",
      isolation: "database_default",
    },
  },
  {
    id: "documents.completeExtraction",
    version: 1,
    owner: "documents",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.complete_student_document_extraction",
    description: "Stores model extraction as reviewable data and automatically projects correctly classified transcript courses into advisory equivalency matching.",
    reads: [
      "document.status",
      "document.category",
      "document.requirementId",
    ],
    writes: [
      "document.status",
      "document.category",
      "document.extraction",
      "enrollment.requirement.status",
      "financial.requiredDocument.status",
      "academics.transcriptCredits",
      "academics.exemptionRecommendations",
    ],
    emits: [
      "document.extraction_completed.v1",
      "student.transcript_credits_imported.v1",
    ],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "documentId + extractionAttempt",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.retryExtraction",
    version: 1,
    owner: "documents",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPlatformService._retry_document_extraction",
    description: "Atomically queues a retryable stored extraction and publishes a new durable worker request without rereading the original in the HTTP request.",
    reads: [
      "document.status",
      "document.category",
      "document.requirementId",
      "document.extraction",
    ],
    writes: ["document.status", "document.extraction"],
    emits: [
      "document.extraction_retry_started.v1",
      "document.extraction_requested.v1",
    ],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
  {
    id: "documents.confirmExtraction",
    version: 1,
    owner: "documents",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.confirm_student_document_extraction",
    description: "Confirms selected non-transcript document fields and projects only safe student-owned fields; retained as an idempotent compatibility path for older transcript reviews.",
    reads: ["document.extraction"],
    writes: [
      "document.status",
      "student.profile",
      "academics.transcriptCredits",
      "academics.exemptionRecommendations",
      "enrollment.requirement.status",
    ],
    emits: [
      "student.transcript_credits_imported.v1",
      "student.profile_updated.v1",
    ],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "financials.recordDeposit",
    version: 1,
    owner: "financials",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.create_deposit_payment",
    description: "Records the processor result once and emits the payment fact.",
    reads: ["admission.offer.status", "financial.deposit.status"],
    writes: [
      "financial.deposit.status",
      "enrollment.requirement.status",
      "financial.remainingBalanceCents",
    ],
    emits: ["payment.deposit_succeeded.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "financials.selectPaymentPlan",
    version: 1,
    owner: "financials",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.select_financial_payment_plan",
    description: "Selects one eligible plan and refreshes the financial projection.",
    reads: [
      "financial.remainingBalanceCents",
      "financial.paymentPlan.status",
    ],
    writes: [
      "financial.paymentPlan.status",
    ],
    emits: ["student_financial.payment_plan_selected.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: true,
      key: "Idempotency-Key",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "serializable",
    },
  },
  {
    id: "studentProfile.update",
    version: 1,
    owner: "student-profile",
    kind: "command",
    implementationStatus: "implemented",
    handler: "PostgresPortalRepository.update_student_profile",
    description: "Updates the student-owned profile under optimistic concurrency.",
    reads: ["student.profile"],
    writes: ["student.profile", "enrollment.requirement.status"],
    emits: ["student.profile_updated.v1"],
    consumes: [],
    synchronousCalls: [],
    idempotency: {
      required: false,
      key: "expectedVersion",
      scope: "aggregate",
    },
    transaction: {
      boundary: "database_and_outbox",
      isolation: "database_default",
    },
  },
] as const satisfies readonly StateEffect[];
